### ISSUE TITLE
it cannot show files

### ISSUE THREAD

**Issue by XuCcc** [Clarence-pan/node-ftp-server-for-docker#1]
```shell
  docker-fs:debug readdir { path: '/' } +7ms                                                                 
  shell ShellExec: "docker" "ps" "--format" "{{.Names}}" +1ms                                                
  shell ["docker" "ps" "--format" "{{.Names}}"]: exit with code: 127 +4ms                                    
  shell ["docker" "ps" "--format" "{{.Names}}"]: end:                                                        
  shell STDOUT:                                                                                              
  shell                                                                                                      
  shell STDERR:                                                                                              
  shell /bin/sh: docker: command not found                                                                   
                                                                                                             
  shell    =>  { err:                                                                                        
   { Error: Command failed: "docker" "ps" "--format" "{{.Names}}"                                            
   /bin/sh: docker: command not found                                                                        
                                                                                                             
       at ChildProcess.exithandler (child_process.js:204:12)                                                 
       at emitTwo (events.js:106:13)                                                                         
       at ChildProcess.emit (events.js:191:7)                                                                
       at maybeClose (internal/child_process.js:886:16)                                                      
       at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)                              
     killed: false,                                                                                          
     code: 127,                                                                                              
     signal: null,                                                                                           
     cmd: '"docker" "ps" "--format" "{{.Names}}"' },                                                         
  retCode: 127 } +0ms                                                                                        
While sending file list, reading directory: Error: Command failed: "docker" "ps" "--format" "{{.Names}}"     
/bin/sh: docker: command not found                                                                           
                                                                                                             
FTP command: QUIT                                                                                            
Client connection ended                                                                                      
Client connection closed                                                                                     
```

npm version **node-v6.10.1-linux-x64**

**Comment by Clarence-pan** [comment]
`   /bin/sh: docker: command not found ` -- this is the main problem. Do you put your `docker` executable's directory in `PATH`?

**Comment by bluetomlee** [comment]
同遇到这个问题，在docker里为什么还需要docker path？

**Comment by Clarence-pan** [comment]
@bluetomlee 这个ftp工具是基于docker命令行的，需要执行docker这个命令
