### ISSUE TITLE
服务可以启动，但无法指定访问的容器

### ISSUE THREAD

**Issue by marbleqi** [Clarence-pan/node-ftp-server-for-docker#3]
服务可以启动，但无法指定访问的容器。
使用ftp工具打开后，提示无法展示远程目录。

**Comment by Clarence-pan** [comment]
求截图和控制台输出

**Comment by Rishon33** [comment]
![image](https://github.com/Clarence-pan/node-ftp-server-for-docker/assets/15354615/860c614e-ec78-4d93-b898-3c010abca092)
```

 docker-fs:debug readdir { path: '/' } +27s
  shell ShellExec: "docker" "ps" "--format" "{{.Names}}" +0ms
  shell ["docker" "ps" "--format" "{{.Names}}"]: exit with code: 127 +5ms
  shell ["docker" "ps" "--format" "{{.Names}}"]: end:
  shell STDOUT:
  shell 
  shell STDERR:
  shell /bin/sh: docker: Permission denied

  shell    =>  {
  err: Error: Command failed: "docker" "ps" "--format" "{{.Names}}"
  /bin/sh: docker: Permission denied
  
      at ChildProcess.exithandler (node:child_process:419:12)
      at ChildProcess.emit (node:events:514:28)
      at maybeClose (node:internal/child_process:1091:16)
      at Socket.<anonymous> (node:internal/child_process:449:11)
      at Socket.emit (node:events:514:28)
      at Pipe.<anonymous> (node:net:323:12) {
    code: 127,
    killed: false,
    signal: null,
    cmd: '"docker" "ps" "--format" "{{.Names}}"'
  },
  retCode: 127
} +0ms
ERROR: <::ffff:192.168.50.180> Error sending file list, reading directory: Error: Command failed: "docker" "ps" "--format" "{{.Names}}"
/bin/sh: docker: Permission denied

Trace: Trace follows
    at FtpServer._logIf (/usr/local/lib/node_modules/ftp-server-for-docker/node_modules/ftpd/lib/FtpServer.js:141:13)
    at FtpConnection._logIf (/usr/local/lib/node_modules/ftp-server-for-docker/node_modules/ftpd/lib/FtpConnection.js:43:22)
    at /usr/local/lib/node_modules/ftp-server-for-docker/node_modules/ftpd/lib/FtpConnection.js:465:12
    at /usr/local/lib/node_modules/ftp-server-for-docker/node_modules/ftpd/lib/glob.js:108:11
    at /usr/local/lib/node_modules/ftp-server-for-docker/lib/docker-fs.js:376:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
<::ffff:192.168.50.180> >> 550 Not a directory
<::ffff:192.168.50.180> << TYPE A
<::ffff:192.168.50.180> FTP command: TYPE A
<::ffff:192.168.50.180> >> 200 OK
<::ffff:192.168.50.180> << REST 0
<::ffff:192.168.50.180> FTP command: REST 0
<::ffff:192.168.50.180> >> 502 Command not implemented.
...
```
