### ISSUE TITLE
树莓派3b+运行出错，arm v7的架构

### ISSUE THREAD

**Issue by ziyoo365** [Clarence-pan/node-ftp-server-for-docker#5]
root@raspberrypi:~# ftp-server-for-docker -H localhost -p 21 --users abc:123456
  ftp-server Listening on port 21 +0ms
FtpServer start listening at localhost:21
(node:4427) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.
  ftp-server Ftp Server error:  { Error: listen EADDRINUSE :::21
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1271:14)
    at listen (net.js:1307:10)
    at Server.listen (net.js:1403:5)
    at FtpServer.(anonymous function) [as listen] (/root/.nvm/versions/node/v6.15.1/lib/node_modules/ftp-server-for-docker/node_modules/ftpd/lib/ftpd.js:171:31)
    at FtpServer.listen (/root/.nvm/versions/node/v6.15.1/lib/node_modules/ftp-server-for-docker/lib/ftp-server.js:98:19)
    at runFtpServer (/root/.nvm/versions/node/v6.15.1/lib/node_modules/ftp-server-for-docker/lib/cli.js:13:10)
    at Array.module.exports (/root/.nvm/versions/node/v6.15.1/lib/node_modules/ftp-server-for-docker/lib/cli.js:86:12)
    at Object.<anonymous> (/root/.nvm/versions/node/v6.15.1/lib/node_modules/ftp-server-for-docker/cli.js:5:25)
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 21 } +29ms
FtpServer got error:  { Error: listen EADDRINUSE :::21
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1271:14)
    at listen (net.js:1307:10)
    at Server.listen (net.js:1403:5)
    at FtpServer.(anonymous function) [as listen] (/root/.nvm/versions/node/v6.15.1/lib/node_modules/ftp-server-for-docker/node_modules/ftpd/lib/ftpd.js:171:31)
    at FtpServer.listen (/root/.nvm/versions/node/v6.15.1/lib/node_modules/ftp-server-for-docker/lib/ftp-server.js:98:19)
    at runFtpServer (/root/.nvm/versions/node/v6.15.1/lib/node_modules/ftp-server-for-docker/lib/cli.js:13:10)
    at Array.module.exports (/root/.nvm/versions/node/v6.15.1/lib/node_modules/ftp-server-for-docker/lib/cli.js:86:12)
    at Object.<anonymous> (/root/.nvm/versions/node/v6.15.1/lib/node_modules/ftp-server-for-docker/cli.js:5:25)
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 21 }

**Comment by ziyoo365** [comment]
nb！问题解决了，原来是端口占用了换一个端口就好，后台运行命令：$nohup ftp-server-for-docker -H localhost -p 66  --users abc:123456 &
遗憾的是部分使用其他linux系统的容器不支持ls -l 的命令，所以无法显示目录内容。要使用docker自身的目录映射了。
注意:使用nodejs版本：v11.5.0运行出错，我使用nvm切换node到v6.15.1版本就可以正常使用了。不过重启系统后会重新变为v11.5.0版本，得配置开机使用默认v6.15.1版本。
